spring:
  datasource:
    driverClassName: org.postgresql.Driver
#    url: postgres://diqoedpniuqmhb:773d62dcd430f76e41d5c1d2d21e8415ac6f85ad22c2c61d012c6f061f14964d@ec2-34-230-231-71.compute-1.amazonaws.com:5432/d6ffu10edtfcoh
#    username : user
#    password : pwd

graphql:
  packages:
    - "fr.kommentaire.server.question"
    - "fr.kommentaire.server.user"